#build settings:
markdown: kramdown #using github pages tutorial recommended syntax
#original theme:
#theme: jekyll-theme-cayman
remote_theme: ShahRukhK/jekyll-theme-minimal-resume

# Site settings
title: Shah-Rukh Khimani
description: Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Shah-Rukh Khimani
user_description: I'm a nomad Computer Scientist, always searching for the next challenge; no task is too scary nor too difficult.
user_title: Computer Sciecnetist, Developer, Philosopher
email: skhimani@outlook.com
# twitter_username: lorem_ipsum
github_username:  ShahRukhK
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
