#build settings:
markdown: kramdown #using github pages tutorial recommended syntax
#original theme: jekyll-theme-cayman
remote_theme: ShahRukhK/resume_jekyll

# Site settings
title: Under Construcion
description: Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: shahrukhk.github.io

# User settings
username: IN Progress
user_description: I'm a nomad Computer Scientist, always searching for the next challenge; no task is too scary nor too difficult.
user_title: Computer Sciecnetist, Developer, Philosopher
email: skhimani@outlook.com
# twitter_username: lorem_ipsum
github_username:  ShahRukhK
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
